library(dplyr)
library(giscoR)

# EU countries vector
eu_iso3_code <- gisco_countrycode |> filter(eu == TRUE)
eu_iso3_code_vec <- eu_iso3_code$ISO3_CODE

# countries vector G20
g20_iso3_code <- gisco_countrycode |> 
  filter(cldr.short.en %in% c("Argentina", 
                              "Australia", 
                              "Brazil",
                              "Canada",
                              "China",
                              "France",
                              "Germany",
                              "India",
                              "Indonesia",
                              "Italy",
                              "Japan",
                              "Mexico",
                              "Russia",
                              "Saudi Arabia",
                              "South Africa",
                              "South Korea",
                              "Turkey",
                              "United Kingdom",
                              "United States"))
g20_iso3_code_vec <- g20_iso3_code$ISO3_CODE

# countries vector OECD
oecd_iso3_code <- gisco_countrycode |> 
  filter(cldr.short.en %in% c("Australia",
                              "Austria",
                              "Belgium",
                              "Canada",
                              "Chile",
                              "Colombia",
                              "Costa Rica",
                              "Czechia",
                              "Denmark",
                              "Estonia",
                              "Finland",
                              "France",
                              "Germany",
                              "Greece",
                              "Hungary",
                              "Iceland",
                              "Ireland",
                              "Israel",
                              "Italy",
                              "Japan",
                              "South Korea",
                              "Latvia",
                              "Lithuania",
                              "Luxembourg",
                              "Mexico",
                              "Netherlands",
                              "New Zealand",
                              "Norway",
                              "Poland",
                              "Portugal",
                              "Slovakia",
                              "Slovenia",
                              "Spain",
                              "Sweden",
                              "Switzerland",
                              "Turkey",
                              "UK",
                              "US"))
oecd_country_vec <- oecd_iso3_code$ISO3_CODE

# all countries dataframe
selected_countrycode <- gisco_countrycode |> 
  select(-eu) |> 
  mutate(eu = if_else(ISO3_CODE %in% eu_iso3_code_vec, 1, 0),
         g20 = if_else(ISO3_CODE %in% g20_iso3_code_vec, 1, 0),
         oecd = if_else(ISO3_CODE %in% oecd_country_vec, 1, 0),
         iso.name.en = case_when(iso.name.en == "Korea (the Republic of)" ~ "Republic of Korea",
                                 iso.name.en == "Netherlands (the)" ~ "Netherlands (Kingdom of the)",
                                 iso.name.en == "Russian Federation (the)" ~ "Russian Federation",
                                 iso.name.en == "Turkey" ~ "Turkiye",
                                 iso.name.en == "United States of America (the)" ~ "United States",
                                 iso.name.en == "Taiwan (Province of China)" ~ "China, Taiwan Province of",
                                 iso.name.en == "Côte d'Ivoire" ~ "Cote d'Ivoire",
                                 iso.name.en == "United Arab Emirates (the)" ~ "United Arab Emirates",
                                 iso.name.en == "Virgin Islands (British)" ~ "British Virgin Islands",
                                 iso.name.en == "Macao" ~ "China, Macao SAR",
                                 iso.name.en == "Congo (the)" ~ "Congo",
                                 iso.name.en == "Congo (the Democratic Republic of the)" ~ "Dem. Rep. of the Congo",
                                 iso.name.en == "Gambia (the)" ~ "Gambia",
                                 iso.name.en == "Lao People's Democratic Republic (the)" ~ "Lao People's Dem. Rep.",
                                 iso.name.en == "Palestine, State of" ~ "State of Palestine",
                                 iso.name.en == "Turks and Caicos Islands (the)" ~ "Turks and Caicos Islands",
                                 iso.name.en == "Virgin Islands (U.S.)" ~ "United States Virgin Islands",
                                 iso.name.en == "Cocos (Keeling) Islands (the)" ~ "Cocos (Keeling) Islands",
                                 iso.name.en == "Falkland Islands (the) [Malvinas]" ~ "Falkland Islands (Malvinas)",
                                 iso.name.en == "Northern Mariana Islands (the)" ~ "Northern Mariana Islands",
                                 iso.name.en == "Wallis and Futuna" ~ "Wallis and Futuna Islands",
                                 iso.name.en == "Réunion" ~ "Reunion",
                                 iso.name.en == "Curaçao" ~ "Curacao",
                                 iso.name.en == "Sudan (the)" ~ "Sudan",
                                 iso.name.en == "Hong Kong" ~ "China, Hong Kong SAR",
                                 iso.name.en == "Philippines (the)" ~ "Philippines",
                                 iso.name.en == "Bahamas (the)" ~ "Bahamas",
                                 iso.name.en == "Venezuela (Bolivarian Republic of)" ~ "Venezuela (Bolivarian Rep. of)",
                                 iso.name.en == "Dominican Republic (the)" ~ "Dominican Republic",
                                 iso.name.en == "British Indian Ocean Territory (the)" ~ "British Indian Ocean Territory",
                                 iso.name.en == "Cayman Islands (the)" ~ "Cayman Islands",
                                 iso.name.en == "Comoros (the)" ~ "Comoros",
                                 iso.name.en == "Korea (the Democratic People's Republic of)" ~ "Dem. People's Rep. of Korea",
                                 iso.name.en == "Faroe Islands (the)" ~ "Faroe Islands",
                                 iso.name.en == "Holy See (the)" ~ "Holy See",
                                 iso.name.en == "Marshall Islands (the)" ~ "Marshall Islands",
                                 iso.name.en == "Moldova (the Republic of)" ~ "Republic of Moldova",
                                 iso.name.en == "Syrian Arab Republic (the)" ~ "Syrian Arab Republic",
                                 iso.name.en == "Tanzania, the United Republic of" ~ "United Republic of Tanzania",
                                 iso.name.en == "Cook Islands (the)" ~ "Cook Islands",
                                 iso.name.en == "Niger (the)" ~ "Niger",
                                 iso.name.en == "Saint Helena, Ascension and Tristan da Cunha" ~ "Saint Helena",
                                 iso.name.en == "United States Minor Outlying Islands (the)" ~ "United States Minor Outlying Islands",
                                 .default = iso.name.en)) |> 
  filter(eu == 1 | g20 == 1 | oecd == 1)

# save countrycode dataframe 
saveRDS(selected_countrycode, "~/international-Trade-Dashboard/data/countrycode.rds")

# all countrycode
all_countrycode <- gisco_countrycode %>% 
  mutate(iso.name.en = case_when(iso.name.en == "Korea (the Republic of)" ~ "Republic of Korea",
                                iso.name.en == "Netherlands (the)" ~ "Netherlands (Kingdom of the)",
                                iso.name.en == "Russian Federation (the)" ~ "Russian Federation",
                                iso.name.en == "Turkey" ~ "Turkiye",
                                iso.name.en == "United States of America (the)" ~ "United States",
                                iso.name.en == "Taiwan (Province of China)" ~ "China, Taiwan Province of",
                                iso.name.en == "Côte d'Ivoire" ~ "Cote d'Ivoire",
                                iso.name.en == "United Arab Emirates (the)" ~ "United Arab Emirates",
                                iso.name.en == "Virgin Islands (British)" ~ "British Virgin Islands",
                                iso.name.en == "Macao" ~ "China, Macao SAR",
                                iso.name.en == "Congo (the)" ~ "Congo",
                                iso.name.en == "Congo (the Democratic Republic of the)" ~ "Dem. Rep. of the Congo",
                                iso.name.en == "Gambia (the)" ~ "Gambia",
                                iso.name.en == "Lao People's Democratic Republic (the)" ~ "Lao People's Dem. Rep.",
                                iso.name.en == "Palestine, State of" ~ "State of Palestine",
                                iso.name.en == "Turks and Caicos Islands (the)" ~ "Turks and Caicos Islands",
                                iso.name.en == "Virgin Islands (U.S.)" ~ "United States Virgin Islands",
                                iso.name.en == "Cocos (Keeling) Islands (the)" ~ "Cocos (Keeling) Islands",
                                iso.name.en == "Falkland Islands (the) [Malvinas]" ~ "Falkland Islands (Malvinas)",
                                iso.name.en == "Northern Mariana Islands (the)" ~ "Northern Mariana Islands",
                                iso.name.en == "Wallis and Futuna" ~ "Wallis and Futuna Islands",
                                iso.name.en == "Réunion" ~ "Reunion",
                                iso.name.en == "Curaçao" ~ "Curacao",
                                iso.name.en == "Sudan (the)" ~ "Sudan",
                                iso.name.en == "Hong Kong" ~ "China, Hong Kong SAR",
                                iso.name.en == "Philippines (the)" ~ "Philippines",
                                iso.name.en == "Bahamas (the)" ~ "Bahamas",
                                iso.name.en == "Venezuela (Bolivarian Republic of)" ~ "Venezuela (Bolivarian Rep. of)",
                                iso.name.en == "Dominican Republic (the)" ~ "Dominican Republic",
                                iso.name.en == "British Indian Ocean Territory (the)" ~ "British Indian Ocean Territory",
                                iso.name.en == "Cayman Islands (the)" ~ "Cayman Islands",
                                iso.name.en == "Comoros (the)" ~ "Comoros",
                                iso.name.en == "Korea (the Democratic People's Republic of)" ~ "Dem. People's Rep. of Korea",
                                iso.name.en == "Faroe Islands (the)" ~ "Faroe Islands",
                                iso.name.en == "Holy See (the)" ~ "Holy See",
                                iso.name.en == "Marshall Islands (the)" ~ "Marshall Islands",
                                iso.name.en == "Moldova (the Republic of)" ~ "Republic of Moldova",
                                iso.name.en == "Syrian Arab Republic (the)" ~ "Syrian Arab Republic",
                                iso.name.en == "Tanzania, the United Republic of" ~ "United Republic of Tanzania",
                                iso.name.en == "Cook Islands (the)" ~ "Cook Islands",
                                iso.name.en == "Niger (the)" ~ "Niger",
                                iso.name.en == "Saint Helena, Ascension and Tristan da Cunha" ~ "Saint Helena",
                                iso.name.en == "United States Minor Outlying Islands (the)" ~ "United States Minor Outlying Islands",
                                .default = iso.name.en))
saveRDS(all_countrycode, "~/international-Trade-Dashboard/data/all_countrycode.rds")




